AlloeHRMSystem.UI/ViewModels/HomeIndexModel/HomeIndexViewModel.cs
using AlloeHRMSystem.Domain.Entities;
using AlloeHRMSystem.Domain.Enums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AlloeHRMSystem.UI.ViewModels.HomeIndexModel
{
    public class HomeIndexViewModel
    {
        public int EmployeeId { get; set; }
        //  public string UserId { get; set; }

        [Display(Name = "First Name")]
        public string Firstname { get; set; }

        [Display(Name = "Last Name")]
        public string Lastname { get; set; }

        [Phone]
        [Display(Name = "Mobile Phone")]
        [DataType(DataType.PhoneNumber)]
        public string Phone { get; set; }

        [EmailAddress]
        public string Email { get; set; }

        [Display(Name = "Home Address")]
        public string HomeAddress { get; set; }
        public Dept? Department { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string JobTitle { get; set; }
        public string Rank { get; set; }
        public string MaritalStatus { get; set; }

        [DataType(DataType.Date)]
        public DateTime? DateOfBirth { get; set; }
        public string Gender { get; set; }
       
    }
}

AlloeHRMSystem.UI/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using AlloeHRMSystem.Domain.Entities;
using AlloeHRMSystem.Domain.IdentityEntities;
using AlloeHRMSystem.Persistence.IServices;
using AlloeHRMSystem.UI.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using AlloeHRMSystem.UI.Security;
using AlloeHRMSystem.UI.LIB;
using AlloeHRMSystem.UI.ViewModels.EmployeeViewModel;

namespace AlloeHRMSystem.UI.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly IEmployeeRepository _employeeRepository;
        private readonly IWebHostEnvironment _hostingEnvironment;
        private readonly ILogger<HomeController> _logger;
        private readonly IAuthorizationService authorizationService;
        private readonly UserManager<AppUser> userManager;

        public EmployeeController(IEmployeeRepository employeeRepository, IWebHostEnvironment hostingEnvironment,
            ILogger<HomeController> logger, IAuthorizationService authorizationService, UserManager<AppUser> userManager)
        {
            _employeeRepository = employeeRepository;
            _hostingEnvironment = hostingEnvironment;
            _logger = logger;
            this.authorizationService = authorizationService;
            this.userManager = userManager;
        }

        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult EditEmployee(int id)
        {
              
             Employee employee =  _employeeRepository.GetEmployee(id);

            EmployeeEditViewModel updateEmployeeViewModel = new EmployeeEditViewModel()
            {
                EmployeeId = employee.EmployeeId,
                Firstname = employee.Firstname,
                Lastname = employee.Lastname,
                Phone = employee.Phone,
                Email = employee.Email,
                HomeAddress = employee.HomeAddress,
                City = employee.City,
                Country = employee.Country,
                BloodType = employee.BloodType,
                MaritalStatus = employee.MaritalStatus,
                Gender = employee.Gender,
                
                Nationality = employee.Nationality,
                HousePhone = employee.HousePhone,
                JobLocation = employee.JobLocation,
                LegalDayOff = employee.LegalDayOff,
                ExistingPhotoPath = employee.PhotoPath

            };

            return View(updateEmployeeViewModel);
        }

        [HttpPost]
        public IActionResult EditEmployee(EmployeeEditViewModel model)
        {
            if (User.Identity.Name != model.Lastname)
                
            if (ModelState.IsValid)
            {
               
                Employee employee = _employeeRepository.GetEmployee(model.EmployeeId);

                employee.EmployeeId = model.EmployeeId;
                employee.Firstname = model.Firstname;
                employee.Lastname = model.Lastname;
                employee.Phone = model.Phone;
                employee.Email = model.Email;
                employee.HomeAddress = model.HomeAddress;
                employee.City = model.City;
                employee.Country = model.Country;
                employee.BloodType = model.BloodType;
                employee.MaritalStatus = model.MaritalStatus;
                employee.DateOfBirth = model.DateOfBirth;
                employee.Gender = model.Gender;
                employee.Nationality = model.Nationality;
                employee.HousePhone = model.HousePhone;
                employee.JobLocation = model.JobLocation;
                employee.LegalDayOff = model.LegalDayOff;

                if (model.Photo != null)
                {
                    if (model.ExistingPhotoPath != null)
                    {
                        string filePath = Path.Combine(_hostingEnvironment.WebRootPath, "images",
                            model.ExistingPhotoPath);
                        System.IO.File.Delete(filePath);
                       
                    }
                    employee.PhotoPath = ProcessUploadedFile(model);
                }

                //if (await User. != employee.AppUser.Id)

                //    return new HttpUnauthorizedResult();

                // return "Personal Info Created Successfully";
                _employeeRepository.UpdateEmployee(employee);

                var successMessage = "Employee Info Updated Successfully. Name: " + employee.Firstname;
                TempData["successAlert"] = successMessage;
                return RedirectToAction("HomeIndex", "Home");
                   

            }
            return View();
                 
        }
        //var successMessage = "Personal Info Created Successfully. Name: " + personalInfo.FirstName;
        //TempData["successAlert"] = successMessage;
        //            return "Personal Info Created Successfully";

        private string ProcessUploadedFile(CreateEmployeeViewModel create)
        {
            string uniqueFileName = null;
            if (create.Photo != null)
            {
                string uploadsFolder = Path.Combine(_hostingEnvironment.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "-" + create.Photo.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    create.Photo.CopyTo(fileStream);
                }
            }
            return uniqueFileName;
        }

        [HttpGet]
        public IActionResult AddProject()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddProject(AddProjectViewModel project)
        {
            if (ModelState.IsValid)
            {
                EmployeeProject newEmployee = new EmployeeProject
                {
                    EmployeeId = project.EmployeeId ,
                 
                    Name = project.Name,
                    Start = project.Start,
                    Finish = project.Finish,
                    Completed = project.Completed,
                    JobPosition = project.JobPosition,
                    ProjectId = project.ProjectId,
                    Notes = project.Notes
                };
                _employeeRepository.AddEmpProject(newEmployee);
                var successMessage = "Project Info Created Successfully. Name: " + newEmployee.EmployeeId;
                TempData["successAlert"] = successMessage;
                // return RedirectToAction(successMessage, "");
                return PartialView("_PartialMessage");
            }
            return View();
        }

        [HttpGet]
        public IActionResult AddCertificate()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddCertificate(AddCertificateViewModel model)
        {
            if (ModelState.IsValid)
            {
                EmployeeCertificate newCertificate = new EmployeeCertificate
                { 
                    EmployeeId = model.EmployeeId,
                    Name = model.Name,
                    Provider = model.Provider,
                 
                    Date = model.Date,
                    Notes = model.Notes
                 
                };
                _employeeRepository.AddEmpCertificate(newCertificate);

                var successMessage = "Certificate Info Updated Successfully. Name: " + newCertificate.EmployeeId;
                TempData["successAlert"] = successMessage;
                // return RedirectToAction(successMessage,"");
                return PartialView("_PartialMessage");
            }
            return View();
        }

        [HttpGet]
        public IActionResult AddEducation()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddEducation(AddEducationViewModel model)
        {
            if (ModelState.IsValid)
            {
                EmployeeEducation newEducation = new EmployeeEducation
                {
                    EmployeeId = model.EmployeeId,
                    Department = model.Department,
                    DegreeId = model.DegreeId,
                    Degree = model.Degree,
                    Institution = model.Institution,
                    StillStudying = model.StillStudying,
                 
                    Notes = model.Notes,
                    Thesis = model.Thesis,
                    EntranceDate = model.EntranceDate,
                    GraduationDate = model.GraduationDate

                };
                _employeeRepository.AddEmpEducation(newEducation);

                var successMessage = "Education InfoCreated Successfully. Name: " + newEducation.EmployeeId;
                TempData["successAlert"] = successMessage;
                // return RedirectToAction( successMessage, "");
                return PartialView("_PartialMessage");
            }
            return View();
        }

        [HttpGet]
        public IActionResult AddEmergencyCall()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddEmergencyCall(AddEmergencyCallViewModel model)
        {
            if (ModelState.IsValid)
            {
                EmployeeEmergencyCall newEmergency = new EmployeeEmergencyCall
                {
                    EmployeeId = model.EmployeeId,
                    Name = model.Name,
                    SurName = model.SurName,
                    RelationTo = model.RelationTo,
                    Phone = model.Phone

                };

AlloeHRMSystem.UI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using AlloeHRMSystem.UI.Models;
using AlloeHRMSystem.Persistence.IServices;
using AlloeHRMSystem.UI.ViewModels;
using AlloeHRMSystem.Domain.Entities;
using AlloeHRMSystem.UI.ViewModels.HomeIndexModel;

namespace AlloeHRMSystem.UI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IEmployeeRepository _employeeRepository;

        public HomeController(ILogger<HomeController> logger, IEmployeeRepository employeeRepository)
        {
            _logger = logger;
            _employeeRepository = employeeRepository;
        }

        //public async Task<IActionResult> Index(string searchString)
        //{
        //    var movies = from m in _context.Movie
        //                 select m;
        //    if (!String.IsNullOrEmpty(searchString))
        //    {
        //        movies = movies.Where(s => s.Title.Contains(searchString));
        //    }
        //    return View(await movies.ToListAsync());
        //}

        [HttpGet]
        public IActionResult Index()
        {

            return View();
        }

        
        public IActionResult HomeIndex(string searchString)
        { 
           var employeeList = _employeeRepository.SearchAllEmployee(searchString);
           if (!String.IsNullOrEmpty(searchString) && !employeeList.Any())
           {
             employeeList = employeeList.Where(t => t.Firstname.ToLower().Contains(searchString)
               || t.Lastname.ToLower().Contains(searchString)
                  || t.JobTitle.ToLower().Contains(searchString)
                 || t.Email.ToLower().Contains(searchString)
                 || t.Phone.Contains(searchString));
           }
           
               var listingResult = employeeList.Select(e => new HomeIndexViewModel
               {
                   EmployeeId = e.EmployeeId,
                   Firstname = e.Firstname,
                   Lastname = e.Lastname,
                   Department = e.Department,
                   JobTitle = e.JobTitle,
                   Rank = e.Rank,
                   Phone = e.Phone,
                   Email = e.Email,
                   City = e.City,
                   Country = e.Country,
                   Gender = e.Gender,
               }).ToList();
            
            return View(listingResult);
        }

        //[HttpPost]
        //public IActionResult Search(string searchString)
        //{
        //    return RedirectToAction("HomeIndex", new { searchString });
            
        //}

    }
}

AlloeHRMSystem.UI/Views/Home/HomeIndex.cshtml
@model IEnumerable<AlloeHRMSystem.UI.ViewModels.HomeIndexModel.HomeIndexViewModel>



@inject SignInManager<AppUser> signInManager

@using AlloeHRMSystem.UI.Security
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService AuthorizationService
@*@model IEnumerable<AlloeHRMSystem.Domain.Entities.Employe*@

@{
    ViewBag.Title = "Index";

}

<h1>HomeIndex</h1>

<br />


<div class="mdi-navigation active ">
    <h4>Please Kindly Update Your Data</h4>
    <p>
        <ul class="nav-item ml-auto style-switch-button">
            <li class="nav-link btn-link">

                <a asp-action="Index" asp-controller="Employee" class="btn btn-primary m-1">Update Info</a>
            </li>
        </ul>

    </p>
</div>

<br />

<form asp-controller="Home" asp-action="HomeIndex" method="get">
    <p>
        Title: <input type="text" name="SearchString">
        <input type="submit" value="Filter" />
    </p>

</form>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.EmployeeId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Firstname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Lastname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Department)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.JobTitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Rank)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Country)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gender)
        </th>
        <th>

        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.EmployeeId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Firstname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Lastname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Department)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.JobTitle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rank)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Country)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gender)
            </td>
            <td>
                
                <a asp-controller="Employee" asp-action="EditEmployee" asp-route-id="@item.EmployeeId">Edit</a>
                
                

                @*<a asp-page="./Details" asp-route-id="@item.UserId">Details</a>*@

                @*@if ((await AuthorizationService.AuthorizeAsync(
              User, item,
               EmployeeOperations.Delete)).Succeeded)
               {
              <text> | </text>
                <a asp-page="./Delete" asp-route-id="@item.ContactId">Delete</a>
               }
                *@
                @*@model ProcRec.Models.Candidat

              @{

               if (!Session["ID"].Equals(id.ToString()))
                 {
                  Session.Abandon();
                  return RedirectToAction("LoginCandidat", "Candidat");
                }*@
            </td>
        </tr>
    }
</table>

AlloeHRMSystem.UI/Views/Home/Index.cshtml
<!DOCTYPE html>
<html>

<head>
    
    <!-- mobile responsive meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- ** Plugins Needed for the Project ** -->
    <!-- Bootstrap -->
    <link href="~/plugins/bootstrap/bootstrap.min.css" rel="stylesheet" />
    <!-- FontAwesome -->
    <link rel="stylesheet" href="plugins/fontawesome/font-awesome.min.css">
    <!-- Animation -->
    <link rel="stylesheet" href="plugins/animate.css">
    <!-- Prettyphoto -->
    <link rel="stylesheet" href="plugins/prettyPhoto.css">
    <!-- Owl Carousel -->
    <link rel="stylesheet" href="plugins/owl/owl.carousel.css">
    <link rel="stylesheet" href="plugins/owl/owl.theme.css">
    <!-- Flexslider -->
    <link rel="stylesheet" href="plugins/flex-slider/flexslider.css">
    <!-- Flexslider -->
    <link rel="stylesheet" href="plugins/cd-hero/cd-hero.css">
    <!-- Style Swicther -->
    <link id="style-switch" href="css/presets/preset3.css" media="screen" rel="stylesheet" type="text/css">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. -->
    <!--[if lt IE 9]>
      <script src="plugins/html5shiv.js"></script>
      <script src="plugins/respond.min.js"></script>
    <![endif]-->
    <!-- Main Stylesheet -->
    @*<link href="css/style.css" rel="stylesheet">*@
    <link href="~/css/site.css" rel="stylesheet" />
    <!--Favicon-->
    <link rel="icon" href="img/favicon/favicon-32x32.png" type="image/x-icon" />
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="img/favicon/favicon-144x144.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="img/favicon/favicon-72x72.png">
    <link rel="apple-touch-icon-precomposed" href="img/favicon/favicon-54x54.png">

</head>


<body background="~/images/back6.jpg">
        <!-- Modal -->
        @*<div class="modal fade" id="login" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                <div class="modal-content">
                    <div class="modal-header tit-up">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title">Employee Login</h4>
                    </div>
                    @*<div class="modal-body customer-box">
                             Nav tabs
                            <ul class="nav nav-tabs">
                                <li><a class="active" href="#Login" data-toggle="tab">Login</a></li>
                                <li><a href="#Registration" data-toggle="tab">Registration</a></li>
                            </ul>
                             Tab panes

                        </div>
                </div>
            </div>
        @*</div>*@
        <!--/ Header end -->
        <!-- Slider start -->
        <section id="home" class="p-0">
            <div id="main-slide" class="cd-hero">
                <ul class="cd-hero-slider">
                    <li class="selected">
                        <div class="overlay2">
                            <img class="" src="images/slider/bg1.jpg" alt="slider">
                        </div>
                        <div class="cd-full-width">
                            <h2>Need To Invent The Future?</h2>
                            <h3> You Can Dream With Us, We'll Achieve Greatness Together</h3>
                            <a asp-action="login" asp-controller="account" class="nav-link cd-btn btn btn-primary white">Login</a>

                        </div> <!-- .cd-full-width -->
                    </li>
                    <li>
                        <div class="overlay2">
                            <img class="" src="images/slider/bg2.jpg" alt="slider">
                        </div>
                        <div class="cd-half-width">
                            <h2>Your Daily Challenge Is An Opportunity To Grow!</h2>
                            <p>We Believed Learning and daily development should be our employee Daily Goal</p>
                            <a asp-action="login" asp-controller="account" class="nav-link cd-btn btn btn-primary white">Login</a>
                        </div> <!-- .cd-half-width -->

                        <div class="cd-half-width cd-img-container">
                            <img src="images/slider/bg-thumb1.png" alt="">
                        </div> <!-- .cd-half-width.cd-img-container -->
                    </li>
                    <li>
                        <div class="overlay2">
                            <img class="" src="images/slider/bg3.jpg" alt="slider">
                        </div>
                        <div class="cd-half-width cd-img-container img-right">
                            <img src="images/slider/bg-thumb2.png" alt="">
                        </div> <!-- .cd-half-width.cd-img-container -->
                        <div class="cd-half-width">
                            <h2>We Care About you And Your Needs!</h2>
                            <p>We do not Only Desire to make profit as an Organization,</p>
                           <p> We also seek wellness and Happiness of our Employee</p>

                            <a asp-action="login" asp-controller="account" class="nav-link cd-btn btn btn-primary white">Login</a>

                            @*<a href="#0" class="cd-btn btn btn-primary white">Start</a>*@

                        </div> <!-- .cd-half-width -->
                    </li>
                    <li class="cd-bg-video">
                        <div class="cd-full-width">
                            <h2>WE ARE HERE TO MAKE IT HAPPEN</h2>
                            <h3>We Making Difference To Great Things Possible</h3>

                            <a asp-action="login" asp-controller="account" class="nav-link cd-btn btn btn-primary white">Login</a>
                        </div> <!-- .cd-full-width -->

                        <div class="cd-bg-video-wrapper" data-video="videos/video">
                            <!-- video element will be loaded using jQuery -->
                        </div> <!-- .cd-bg-video-wrapper -->
                    </li>
                </ul>
                <!--/ cd-hero-slider -->

                <div class="cd-slider-nav">
                    <nav>
                        <span class="cd-marker item-1"></span>
                        <ul>
                            <li class="selected"><a href="#0"><i class="fa fa-bicycle"></i> Invent</a></li>
                            <li><a href="#0"><i class="fa fa-book"></i> Growth</a></li>
                            <li><a href="#0"><i class="fa fa-money"></i> Care</a></li>
                            <li class="video"><a href="#0"><i class="fa fa-video-camera"></i> Video</a></li>
                        </ul>
                    </nav>
                </div> <!-- .cd-slider-nav -->

            </div>
            <!--/ Main slider end -->
        </section>
        <!--/ Slider end -->
        @*<div id="back-to-top" data-spy="affix" data-offset-top="10" class="back-to-top affix position-fixed">
            <button class="btn btn-primary" title="Back to Top"><i class="fa fa-angle-double-up"></i></button>
        </div>*@




        <!-- jQuery -->
        <script src="plugins/jQuery/jquery.min.js"></script>
        <!-- Bootstrap JS -->
        <script src="plugins/bootstrap/bootstrap.min.js"></script>
        <!-- Style Switcher -->
        <script type="text/javascript" src="plugins/style-switcher.js"></script>
        <!-- Owl Carousel -->
        <script type="text/javascript" src="plugins/owl/owl.carousel.js"></script>
        <!-- PrettyPhoto -->
        <script type="text/javascript" src="plugins/jquery.prettyPhoto.js"></script>
        <!-- Bxslider -->
        <script type="text/javascript" src="plugins/flex-slider/jquery.flexslider.js"></script>
        <!-- CD Hero slider -->
        <script type="text/javascript" src="plugins/cd-hero/cd-hero.js"></script>
        <!-- Isotope -->
        <script type="text/javascript" src="plugins/isotope.js"></script>
        <script type="text/javascript" src="plugins/ini.isotope.js"></script>
        <!-- Wow Animation -->
        <script type="text/javascript" src="plugins/wow.min.js"></script>
        <!-- Eeasing -->
        <script type="text/javascript" src="plugins/jquery.easing.1.3.js"></script>
        <!-- Counter -->
        <script type="text/javascript" src="plugins/jquery.counterup.min.js"></script>
        <!-- Waypoints -->
        <script type="text/javascript" src="plugins/waypoints.min.js"></script>
        <!-- google map -->
        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"></script>
        <script src="plugins/google-map/gmap.js"></script>

        <!-- Main Script -->
        <script src="js/script.js"></script>

    </body>

</html>